---
title: "01_visualizacion_datos"
format: 
  html:
    embed-resources: true
    self-contained-math: true
---

```{r}
library(tidyverse)

#Cargo los datos 
df <- read_csv("../data/DATA (1).csv")
colnames(df)


#Seleccionar y renombrar las variables numéricas de interés
df_num <- df %>%
  transmute(
    Edad = factor(`1`, levels = 1:3, 
                  labels = c("18-21", "22-25", "26+")),
    Beca = factor(`4`, levels = 1:5, 
                  labels = c("Ninguna", "25%", "50%", "75%", "Completa")),
    Salario = factor(`8`, levels = 1:5,
                     labels = c("135-200", "201-270", "271-340", "341-410", "410+")),
    Hermanos = factor(`13`, levels = 1:5,
                      labels = c("1", "2", "3", "4", "5+")),
    EstudioSemanal = factor(`17`, levels = 1:5,
                            labels = c("0h", "<5h", "6-10h", "11-20h", "20h+")),
    GPA_Ultimo = factor(`29`, levels = 1:5,
                        labels = c("<2.0", "2.0-2.49", "2.5-2.99", "3.0-3.49", "3.5+")),
    GPA_Esperado = factor(`30`, levels = 1:5,
                          labels = c("<2.0", "2.0-2.49", "2.5-2.99", "3.0-3.49", "3.5+"))
  )

#Pasar a formato largo
df_num_long <- df_num %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Categoria") %>%
  filter(!is.na(Categoria))

#Seleccionar y renombrar las variables categóricas de interés
df_cat <- df %>%
  transmute(
    Extracurriculares = factor(`6`, levels = c(1,2), labels = c("Si", "No")), # Regular artistic/sports activity
    Instituto = factor(`3`, levels = c(1, 2, 3), labels = c("Privado", "Estatal", "Otro")),
    Transporte = factor(`9`, levels = c(1,2,3,4), labels = c("Bus", "Privado/Taxi", "Bicicleta", "Otro")),
    Pareja = factor(`17`, levels = c(1, 2), labels = c("Si", "No")),
    Sexo = factor(`2`,levels = c(1,2), labels = c("Femenino", "Masculino")),
    TrabajoAdicional = factor(`5`, levels = c(1,2), labels = c("Si", "No"))
  )

#Pasar a formato largo 
df_cat_long <- df_cat %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Categoria") %>%
  filter(!is.na(Categoria))

```

```{r fig.height=5, fig.path='plots/', fig.width=7, dpi=300}
#| label: Distribución de variables numéricas
#Gráfico de barras variables numéricas
ggplot(df_num_long, aes(y = Categoria, fill = Categoria)) +
  geom_bar() +
  facet_wrap(~ Variable, scales = "free") +
  labs(title = "Distribución de variables seleccionadas",
       x = "Frecuencia", y = "Categorías") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r fig.height=5, fig.path='plots/', fig.width=7, dpi=300}
#| label: Distribución de variables categóricas
#Gráfico de barras variables categóricas
ggplot(df_cat_long, aes(y = Categoria, fill = Categoria)) +
  geom_bar() +
  facet_wrap(~ Variable, scales = "free") +
  labs(title = "Distribución de variables categóricas seleccionadas",
       x = "Frecuencia", y = "Categorías") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r fig.height=5, fig.path='plots/', fig.width=7, dpi=300}
#| label: Proporción de GPA esperado según tipo de beca
#Proporción de GPA esperado según tipo de beca
ggplot(df_num, aes(x = Beca, fill = GPA_Esperado)) +
  geom_bar(position = "fill") +
  labs(title = "Proporción de GPA esperado según tipo de beca",
       x = "Tipo de beca", y = "Proporción", fill = "GPA esperado") +
  theme_minimal()
```

```{r fig.height=5, fig.path='plots/', fig.width=7, dpi=300}
#| label: Horas de estudio por semana según edad
#Horas de estudio por semana según edad
ggplot(df_num, aes(x = Edad, fill = EstudioSemanal)) +
  geom_bar(position = "dodge") +  
  labs(title = "Horas de estudio por semana según edad",
       x = "Edad", y = "Cantidad de personas", fill = "Estudio semanal") +
  theme_minimal()
```
